config/routes.rb
Rails.application.routes.draw do
  resources :student_but_dumbs
  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/student_but_dumb.rb
class StudentButDumb < ApplicationRecord

validates_presence_of :name


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/student_but_dumbs_controller.rb
class StudentButDumbsController < ApplicationController
  before_action :set_student_but_dumb, only: %i[ show edit update destroy ]

  # GET /student_but_dumbs or /student_but_dumbs.json
  def index
    @student_but_dumbs = StudentButDumb.all
  end

  # GET /student_but_dumbs/1 or /student_but_dumbs/1.json
  def show
  end

  # GET /student_but_dumbs/new
  def new
    @student_but_dumb = StudentButDumb.new
  end

  # GET /student_but_dumbs/1/edit
  def edit
  end

  # POST /student_but_dumbs or /student_but_dumbs.json
  def create
    @student_but_dumb = StudentButDumb.new(student_but_dumb_params)

    respond_to do |format|
      if @student_but_dumb.save
        format.html { redirect_to student_but_dumb_url(@student_but_dumb), notice: "Student but dumb was successfully created." }
        format.json { render :show, status: :created, location: @student_but_dumb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_but_dumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_but_dumbs/1 or /student_but_dumbs/1.json
  def update
    respond_to do |format|
      if @student_but_dumb.update(student_but_dumb_params)
        format.html { redirect_to student_but_dumb_url(@student_but_dumb), notice: "Student but dumb was successfully updated." }
        format.json { render :show, status: :ok, location: @student_but_dumb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_but_dumb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_but_dumbs/1 or /student_but_dumbs/1.json
  def destroy
    @student_but_dumb.destroy

    respond_to do |format|
      format.html { redirect_to student_but_dumbs_url, notice: "Student but dumb was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_but_dumb
      @student_but_dumb = StudentButDumb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_but_dumb_params
      params.require(:student_but_dumb).permit(:offset_from_roy, :name, :doctor_e_watching, :age, :in_syria)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.fetch(:student, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_but_dumbs_helper.rb
module StudentButDumbsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/student_but_dumbs/_form.html.erb
<%= form_with(model: student_but_dumb) do |form| %>
  <% if student_but_dumb.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student_but_dumb.errors.count, "error") %> prohibited this student_but_dumb from being saved:</h2>

      <ul>
        <% student_but_dumb.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :offset_from_roy, style: "display: block" %>
    <%= form.number_field :offset_from_roy %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :doctor_e_watching, style: "display: block" %>
    <%= form.check_box :doctor_e_watching %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :in_syria, style: "display: block" %>
    <%= form.check_box :in_syria %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/student_but_dumbs/_student_but_dumb.html.erb
<div id="<%= dom_id student_but_dumb %>">
  <p>
    <strong>Offset from roy:</strong>
    <%= student_but_dumb.offset_from_roy %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= student_but_dumb.name %>
  </p>

  <p>
    <strong>Doctor e watching:</strong>
    <%= student_but_dumb.doctor_e_watching %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= student_but_dumb.age %>
  </p>

  <p>
    <strong>In syria:</strong>
    <%= student_but_dumb.in_syria %>
  </p>

</div>

app/views/student_but_dumbs/edit.html.erb
<h1>Editing student but dumb</h1>

<%= render "form", student_but_dumb: @student_but_dumb %>

<br>

<div>
  <%= link_to "Show this student but dumb", @student_but_dumb %> |
  <%= link_to "Back to student but dumbs", student_but_dumbs_path %>
</div>

app/views/student_but_dumbs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Student but dumbs</h1>

<div id="student_but_dumbs">
  <% @student_but_dumbs.each do |student_but_dumb| %>
    <%= render student_but_dumb %>
    <p>
      <%= link_to "Show this student but dumb", student_but_dumb %>
    </p>
  <% end %>
</div>

<%= link_to "New student but dumb", new_student_but_dumb_path %>

app/views/student_but_dumbs/new.html.erb
<h1>New student but dumb</h1>

<%= render "form", student_but_dumb: @student_but_dumb %>

<br>

<div>
  <%= link_to "Back to student but dumbs", student_but_dumbs_path %>
</div>

app/views/student_but_dumbs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student_but_dumb %>

<div>
  <%= link_to "Edit this student but dumb", edit_student_but_dumb_path(@student_but_dumb) %> |
  <%= link_to "Back to student but dumbs", student_but_dumbs_path %>

  <%= button_to "Destroy this student but dumb", @student_but_dumb, method: :delete %>
</div>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Students</h1>

<div id="students">
  <% @students.each do |student| %>
    <%= render student %>
    <p>
      <%= link_to "Show this student", student %>
    </p>
  <% end %>
</div>

<%= link_to "New student", new_student_path %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student %>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>